import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import StoryblokProvider from "@/src/app/components/StoryblokProvider";

import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "storyblok next portfolio",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en" data-scroll-behavior="smooth" className="scroll-smooth">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-50 `}
        >
          <header className="max-w-4xl mx-auto flex justify-between items-center px-5">
            <Link href={"/"}>
              <Image
                src="/next.svg"
                alt="TravelersHub Logo"
                width={120}
                height={38}
              />
            </Link>
            <nav className="flex gap-5 px-4 py-4 ">
              <Link className="text-sm" href={"/"}>
                Home
              </Link>
              <Link className="text-sm" href={"/articles"}>
                Articles
              </Link>
            </nav>
          </header>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
